blog_add_tag:
    path:    /tags/add
    defaults: { _controller: BlogBundle:Tag:add }

login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }

login_check:
    path: /login_check

logout:
    path: /logout

blog_homepage:
    path: /
    defaults: { _controller: BlogBundle:Default:index }