login:
    path: /login
    defaults: { _controller: BlogBundle:User:login }

login_check:
    path: /login_check

logout:
    path: /logout

blog_homepage:
    path: /
    defaults: { _controller: BlogBundle:Entry:index }

blog_index_tag:
    path:    /tags
    defaults: { _controller: BlogBundle:Tag:index }

blog_add_tag:
    path:    /tags/add
    defaults: { _controller: BlogBundle:Tag:add }

blog_delete_tag:
    path:    /tags/delete/{id}
    defaults: { _controller: BlogBundle:Tag:delete }

blog_add_category:
    path:    /categories/add
    defaults: { _controller: BlogBundle:Category:add }

blog_index_category:
    path:    /categories
    defaults: { _controller: BlogBundle:Category:index }

blog_delete_category:
    path:    /categories/delete/{id}
    defaults: { _controller: BlogBundle:Category:delete }

blog_edit_category:
    path:   /categories/edit/{id}
    defaults: { _controller: BlogBundle:Category:edit }

blog_add_entry:
    path:   /entries/add
    defaults: { _controller: BlogBundle:Entry:add}

blog_delete_entry:
    path:   /entries/delete/{id}
    defaults: { _controller: BlogBundle:Entry:delete }

blog_edit_entry:
    path:   /entries/edit/{id}
    defaults: { _controller: BlogBundle:Entry:edit }