BlogBundle\Entity\Tag:
    properties:
        name:
            - NotBlank: {message: "El nombre no puede estar vacío"}
            - Length:
                min: 2
                minMessage: "El nombre tiene que tener mas de 2 caracteres"